import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CommonService {
  private themeWrapper: any = document.querySelector('html');
public productType
theme = {
  'default': {
    '--PRIMARYCOLOR' : '#f3b02d',
    '--SECONDARYCOLOR' : '#d22636',
    '--DARKBOXSHADOW' : '#0000004d',  
    '--LINK' : '#007bff',   
    '--BGLIGHTER' : '#f2f5f8',
    '--BGDARK' : '#333333',
    '--BGWHITE' : '#ffffff',
    '--TXTDARK' : '#666666',
    '--TXTDARKER' : '#333333',
    '--TXTBLACK' : '#000000',
    '--TXTLIGHT' : '#8b8f97',
    '--TXTLIGHTER' : '#cccccc',
    '--TXTWHITE' : '#ffffff',  
    '--BDRLIGHTER' : '#efefef',
    '--BDRLIGHT' : '#9e9e9e',
    '--BDRREGULAR':'#cccccc',
    '--PRIMARYREGULARFONT':'OpenSans-Regular',
    '--PRIMARYLIGHTFONT':'OpenSans-Light',
    '--PRIMARYMEDIUMFONT':'OpenSans-Medium',
    '--PRIMARYSEMIBOLDFONT':'OpenSans-SemiBold',
    '--PRIMARYBOLDFONT':'OpenSans-Bold'      
  },
  'MH': {
    '--PRIMARYCOLOR' : '#19286e',
    '--SECONDARYCOLOR' : '#19286e',
    '--DARKBOXSHADOW' : '#0000004d',  
    '--LINK' : '#007bff',   
    '--BGLIGHTER' : '#f2f5f8',
    '--BGDARK' : '#333333',
    '--BGWHITE' : '#ffffff',
    '--TXTDARK' : '#666666',
    '--TXTDARKER' : '#333333',
    '--TXTBLACK' : '#000000',
    '--TXTLIGHT' : '#8b8f97',
    '--TXTLIGHTER' : '#cccccc',
    '--TXTWHITE' : '#ffffff',  
    '--BDRLIGHTER' : '#efefef',
    '--BDRLIGHT' : '#9e9e9e',
    '--BDRREGULAR':'#cccccc',
    '--PRIMARYREGULARFONT':'OpenSans-Regular',
    '--PRIMARYLIGHTFONT':'OpenSans-Light',
    '--PRIMARYMEDIUMFONT':'OpenSans-Medium',
    '--PRIMARYSEMIBOLDFONT':'OpenSans-SemiBold',
    '--PRIMARYBOLDFONT':'OpenSans-Bold'      
  },
  'A3': {
    '--PRIMARYCOLOR' : '#002677',
    '--SECONDARYCOLOR' : '#416BF6',
    '--DARKBOXSHADOW' : '#0000004d',  
    '--LINK' : '#002677',   
    '--BGLIGHTER' : '#f2f5f8',
    '--BGDARK' : '#333333',
    '--BGWHITE' : '#ffffff',
    '--TXTDARK' : '#666666',
    '--TXTDARKER' : '#333333',
    '--TXTBLACK' : '#000000',
    '--TXTLIGHT' : '#8b8f97',
    '--TXTLIGHTER' : '#cccccc',
    '--TXTWHITE' : '#ffffff',  
    '--BDRLIGHTER' : '#efefef',
    '--BDRLIGHT' : '#dcdcdc',
    '--BDRREGULAR':'#cccccc',
    '--PRIMARYREGULARFONT':'OpenSans-Regular',
    '--PRIMARYLIGHTFONT':'OpenSans-Light',
    '--PRIMARYMEDIUMFONT':'OpenSans-Medium',
    '--PRIMARYSEMIBOLDFONT':'OpenSans-SemiBold',
    '--PRIMARYBOLDFONT':'OpenSans-Bold'      
  },
  'TR': {
    '--PRIMARYCOLOR' : '#000000',
    '--SECONDARYCOLOR' : '#ffe900',
    '--DARKBOXSHADOW' : '#0000004d',  
    '--LINK' : '#007bff',   
    '--BGLIGHTER' : '#f2f5f8',
    '--BGDARK' : '#333333',
    '--BGWHITE' : '#ffffff',
    '--TXTDARK' : '#666666',
    '--TXTDARKER' : '#333333',
    '--TXTBLACK' : '#000000',
    '--TXTLIGHT' : '#8b8f97',
    '--TXTLIGHTER' : '#cccccc',
    '--TXTWHITE' : '#ffffff',  
    '--BDRLIGHTER' : '#efefef',
    '--BDRLIGHT' : '#9e9e9e',
    '--BDRREGULAR':'#cccccc',
    '--PRIMARYREGULARFONT':'OpenSans-Regular',
    '--PRIMARYLIGHTFONT':'OpenSans-Light',
    '--PRIMARYMEDIUMFONT':'OpenSans-Medium',
    '--PRIMARYSEMIBOLDFONT':'OpenSans-SemiBold',
    '--PRIMARYBOLDFONT':'OpenSans-Bold'    
  },
  'KM': {
    '--PRIMARYCOLOR' : '#dc0c23',
    '--SECONDARYCOLOR' : '#299147',
    '--DARKBOXSHADOW' : '#0000004d',  
    '--LINK' : '#007bff',   
    '--BGLIGHTER' : '#f2f5f8',
    '--BGDARK' : '#333333',
    '--BGWHITE' : '#ffffff',
    '--TXTDARK' : '#666666',
    '--TXTDARKER' : '#333333',
    '--TXTBLACK' : '#000000',
    '--TXTLIGHT' : '#8b8f97',
    '--TXTLIGHTER' : '#cccccc',
    '--TXTWHITE' : '#ffffff',  
    '--BDRLIGHTER' : '#efefef',
    '--BDRLIGHT' : '#9e9e9e',
    '--BDRREGULAR':'#cccccc',
    '--PRIMARYREGULARFONT':'OpenSans-Regular',
    '--PRIMARYLIGHTFONT':'OpenSans-Light',
    '--PRIMARYMEDIUMFONT':'OpenSans-Medium',
    '--PRIMARYSEMIBOLDFONT':'OpenSans-SemiBold',
    '--PRIMARYBOLDFONT':'OpenSans-Bold'    
  },
  'WN': {
    '--PRIMARYCOLOR' : '#324FB0',
    '--SECONDARYCOLOR' : '#FEBE3C',
    '--DARKBOXSHADOW' : '#0000004d',  
    '--LINK' : '#286aa4',   
    '--BGLIGHTER' : '#f2f5f8',
    '--BGDARK' : '#333333',
    '--BGWHITE' : '#ffffff',
    '--TXTDARK' : '#666666',
    '--TXTDARKER' : '#333333',
    '--TXTBLACK' : '#000000',
    '--TXTLIGHT' : '#8b8f97',
    '--TXTLIGHTER' : '#cccccc',
    '--TXTWHITE' : '#ffffff',  
    '--BDRLIGHTER' : '#efefef',
    '--BDRLIGHT' : '#9e9e9e',
    '--BDRREGULAR':'#cccccc',
    '--PRIMARYREGULARFONT':'OpenSans-Regular',
    '--PRIMARYLIGHTFONT':'OpenSans-Light',
    '--PRIMARYMEDIUMFONT':'OpenSans-Medium',
    '--PRIMARYSEMIBOLDFONT':'OpenSans-SemiBold',
    '--PRIMARYBOLDFONT':'OpenSans-Bold'    
  },
  'AMAL': {
    '--PRIMARYCOLOR' : '#0261B1',
    '--SECONDARYCOLOR' : '#07b9e9',
    '--DARKBOXSHADOW' : '#0000004d',  
    '--LINK' : '#007bcb',   
    '--BGLIGHTER' : '#e6e8e5',
    '--BGDARK' : '#cccccc',
    '--BGWHITE' : '#ffffff',
    '--TXTDARK' : '#000000',
    '--TXTDARKER' : '#333333',
    '--TXTBLACK' : '#000000',
    '--TXTLIGHT' : '#666666',
    '--TXTLIGHTER' : '#cccccc',
    '--TXTWHITE' : '#ffffff',  
    '--BDRLIGHTER' : '#efefef',
    '--BDRLIGHT' : '#E6E6E6',
    '--BDRREGULAR':'#cccccc',
    '--PRIMARYREGULARFONT':'OpenSans-Regular',
    '--PRIMARYLIGHTFONT':'OpenSans-Light',
    '--PRIMARYMEDIUMFONT':'OpenSans-Medium',
    '--PRIMARYSEMIBOLDFONT':'OpenSans-SemiBold',
    '--PRIMARYBOLDFONT':'OpenSans-Bold'    
  },
  'CT': {
    '--PRIMARYCOLOR' : '#0075CB',
    '--SECONDARYCOLOR' : '#1E4FA0',
    '--DARKBOXSHADOW' : '#0000004d',  
    '--LINK' : '#001764',   
    '--BGLIGHTER' : '#f2f5f8',
    '--BGDARK' : '#cccccc',
    '--BGWHITE' : '#ffffff',
    '--TXTDARK' : '#000000',
    '--TXTDARKER' : '#333333',
    '--TXTBLACK' : '#000000',
    '--TXTLIGHT' : '#666666',
    '--TXTLIGHTER' : '#cccccc',
    '--TXTWHITE' : '#ffffff',  
    '--BDRLIGHTER' : '#efefef',
    '--BDRLIGHT' : '#E6E6E6',
    '--BDRREGULAR':'#cccccc',
    '--PRIMARYREGULARFONT':'OpenSans-Regular',
    '--PRIMARYLIGHTFONT':'OpenSans-Light',
    '--PRIMARYMEDIUMFONT':'OpenSans-Medium',
    '--PRIMARYSEMIBOLDFONT':'OpenSans-SemiBold',
    '--PRIMARYBOLDFONT':'OpenSans-Bold'    
  },
  'RM': {
    '--PRIMARYCOLOR' : '#FFB70D',
    '--SECONDARYCOLOR' : '#286aa4',
    '--DARKBOXSHADOW' : '#0000004d',  
    '--LINK' : '#286aa4',   
    '--BGLIGHTER' : '#f2f5f8',
    '--BGDARK' : '#333333',
    '--BGWHITE' : '#ffffff',
    '--TXTDARK' : '#666666',
    '--TXTDARKER' : '#333333',
    '--TXTBLACK' : '#000000',
    '--TXTLIGHT' : '#8b8f97',
    '--TXTLIGHTER' : '#cccccc',
    '--TXTWHITE' : '#ffffff',  
    '--BDRLIGHTER' : '#efefef',
    '--BDRLIGHT' : '#9e9e9e',
    '--BDRREGULAR':'#cccccc',
    '--PRIMARYREGULARFONT':'OpenSans-Regular',
    '--PRIMARYLIGHTFONT':'OpenSans-Light',
    '--PRIMARYMEDIUMFONT':'OpenSans-Medium',
    '--PRIMARYSEMIBOLDFONT':'OpenSans-SemiBold',
    '--PRIMARYBOLDFONT':'OpenSans-Bold'    
  },
  'AK': {
    '--PRIMARYCOLOR' : '#e10000',
    '--SECONDARYCOLOR' : '#4B4FA6',
    '--DARKBOXSHADOW' : '#0000004d',  
    '--LINK' : '#4B4FA6',   
    '--BGLIGHTER' : '#f2f5f8',
    '--BGDARK' : '#333333',
    '--BGWHITE' : '#ffffff',
    '--TXTDARK' : '#666666',
    '--TXTDARKER' : '#333333',
    '--TXTBLACK' : '#000000',
    '--TXTLIGHT' : '#8b8f97',
    '--TXTLIGHTER' : '#cccccc',
    '--TXTWHITE' : '#ffffff',  
    '--BDRLIGHTER' : '#efefef',
    '--BDRLIGHT' : '#9e9e9e',
    '--BDRREGULAR':'#cccccc',
    '--PRIMARYREGULARFONT':'OpenSans-Regular',
    '--PRIMARYLIGHTFONT':'OpenSans-Light',
    '--PRIMARYMEDIUMFONT':'OpenSans-Medium',
    '--PRIMARYSEMIBOLDFONT':'OpenSans-SemiBold',
    '--PRIMARYBOLDFONT':'OpenSans-Bold'    
  },
  'WY': {
    '--PRIMARYCOLOR' : '#008bae',
    '--SECONDARYCOLOR' : '#008bae',
    '--DARKBOXSHADOW' : '#0000004d',  
    '--LINK' : '#0c8cff',   
    '--BGLIGHTER' : '#f2f5f8',
    '--BGDARK' : '#333333',
    '--BGWHITE' : '#ffffff',
    '--TXTDARK' : '#666666',
    '--TXTDARKER' : '#333333',
    '--TXTBLACK' : '#000000',
    '--TXTLIGHT' : '#8b8f97',
    '--TXTLIGHTER' : '#cccccc',
    '--TXTWHITE' : '#ffffff',  
    '--BDRLIGHTER' : '#efefef',
    '--BDRLIGHT' : '#9e9e9e',
    '--BDRREGULAR':'#cccccc',
    '--PRIMARYREGULARFONT':'OpenSans-Regular',
    '--PRIMARYLIGHTFONT':'OpenSans-Light',
    '--PRIMARYMEDIUMFONT':'OpenSans-Medium',
    '--PRIMARYSEMIBOLDFONT':'OpenSans-SemiBold',
    '--PRIMARYBOLDFONT':'OpenSans-Bold'    
  },
  'G3': {
    '--PRIMARYCOLOR' : '#FF5A00',
    '--SECONDARYCOLOR' : '#004c81',
    '--DARKBOXSHADOW' : '#0000004d',  
    '--LINK' : '#004c81',   
    '--BGLIGHTER' : '#f2f5f8',
    '--BGDARK' : '#333333',
    '--BGWHITE' : '#ffffff',
    '--TXTDARK' : '#666666',
    '--TXTDARKER' : '#333333',
    '--TXTBLACK' : '#000000',
    '--TXTLIGHT' : '#8b8f97',
    '--TXTLIGHTER' : '#cccccc',
    '--TXTWHITE' : '#ffffff',  
    '--BDRLIGHTER' : '#efefef',
    '--BDRLIGHT' : '#9e9e9e',
    '--BDRREGULAR':'#cccccc',
    '--PRIMARYREGULARFONT':'OpenSans-Regular',
    '--PRIMARYLIGHTFONT':'OpenSans-Light',
    '--PRIMARYMEDIUMFONT':'OpenSans-Medium',
    '--PRIMARYSEMIBOLDFONT':'OpenSans-SemiBold',
    '--PRIMARYBOLDFONT':'OpenSans-Bold'    
  },
  'JA': {
    '--PRIMARYCOLOR' : '#153e69',
    '--SECONDARYCOLOR' : '#9E202D',
    '--DARKBOXSHADOW' : '#0000004d',  
    '--LINK' : '#004c81',   
    '--BGLIGHTER' : '#f2f5f8',
    '--BGDARK' : '#333333',
    '--BGWHITE' : '#ffffff',
    '--TXTDARK' : '#666666',
    '--TXTDARKER' : '#333333',
    '--TXTBLACK' : '#000000',
    '--TXTLIGHT' : '#8b8f97',
    '--TXTLIGHTER' : '#cccccc',
    '--TXTWHITE' : '#ffffff',  
    '--BDRLIGHTER' : '#efefef',
    '--BDRLIGHT' : '#9e9e9e',
    '--BDRREGULAR':'#cccccc',
    '--PRIMARYREGULARFONT':'OpenSans-Regular',
    '--PRIMARYLIGHTFONT':'OpenSans-Light',
    '--PRIMARYMEDIUMFONT':'OpenSans-Medium',
    '--PRIMARYSEMIBOLDFONT':'OpenSans-SemiBold',
    '--PRIMARYBOLDFONT':'OpenSans-Bold'    
  }
}

  constructor() { }
  

  public themeCall(){
    this.productType=sessionStorage.getItem("themeCode");  
    for (const [key, value] of Object.entries(this.theme[this.productType])) {
      this.themeWrapper.style.setProperty(key, value);
    }
  }
}
